#!/bin/bash
# Created by http://www.vps-murah.net
# Dilarang Keras Mengambil/mencuplik/mengcopy sebagian atau seluruh script ini.
# Hak Cipta HostingTermurah.net (Dilindungi Undang-Undang nomor 19 Tahun 2002)
if [[ -e /etc/debian_version ]]; then
	OS=debian
	RCLOCAL='/etc/rc.local'
elif [[ -e /etc/centos-release || -e /etc/redhat-release ]]; then
	OS=centos
	RCLOCAL='/etc/rc.d/rc.local'
	chmod +x /etc/rc.d/rc.local
else
	echo "Sepertinya Anda tidak menjalankan installer ini pada sistem Debian, Ubuntu atau CentOS"
	exit
fi
color1='\e[031;1m'
color2='\e[34;1m'
color3='\e[0m'
echo "---------------- ยินดีต้อนรับสู่ Premium Script Menu ----------------"
	echo ""
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')

	echo -e "\e[032;1mCPU model:\e[0m $cname"
	echo -e "\e[032;1mNumber of cores:\e[0m $cores"
	echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
	echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
	echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
	echo -e "\e[032;1mSystem uptime:\e[0m $up"
	echo -e "------------------------------------------------------------------------------"
	echo -e "เกี่ยวกับ SSH และ OpenVPN"
	echo -e "${color1}1${color3}.  สร้างบัญชี SSH & OpenVPN (${color2}user-add${color3})"
	echo -e "${color1}2${color3}.  สร้างบัญชีแบบสุ่ม SSH/OpenVPN (${color2}user-generate${color3})"
	echo -e "${color1}3${color3}.  สร้างบัญชีทดลอง SSH & OpenVPN (${color2}trial${color3})"
	echo -e "${color1}4${color3}.  เพิ่มเวลาที่ใช้งานของบัญชี SSH & OpenVPN (${color2}user-aktif${color3})"
	echo -e "${color1}5${color3}.  เปลี่ยนรหัสผ่านบัญชี SSH/OpenVPN (${color2}user-password${color3})"
	echo -e "${color1}6${color3}.  Ban บัญชีที่เชื่อมต่อเกินกำหนด (${color2}user-ban${color3})"
	echo -e "${color1}7${color3}.  ยกเลิก Ban บัญชี SSH & OpenVPN (${color2}user-unban${color3})"
	echo -e "${color1}8${color3}.  ล็อกผู้ใช้ SSH & OpenVPN (${color2}user-lock${color3})"
	echo -e "${color1}9${color3}.  ปลดล็อกผู้ใช้ SSH & OpenVPN (${color2}user-unlock${color3})"
	echo -e "${color1}10${color3}. ลบบัญชี SSH & OpenVPN (${color2}user-delete${color3})"
	echo -e "${color1}11${color3}. ดูข้อมูลผู้ใช้ SSH & OpenVPN (${color2}user-detail${color3})"
	echo -e "${color1}12${color3}. แสดงรายชื่อผู้ใช้ SSH และ OpenVPN (${color2}user-list${color3})"
	echo -e "${color1}13${color3}. ตรวจสอบการเข้าสู่ระบบ Dropbear, OpenSSH และ OpenVPN (${color2}user-login${color3})"
	echo -e "${color1}14${color3}. ดูบันทึกการเข้าสู่ระบบ Dropbear & OpenSSH (${color2}user-log${color3})"
	echo -e "${color1}15${color3}. เตะบัญชีที่เชื่อมต่อเกินกำหนด (${color2}user-limit${color3})"
	echo -e "${color1}16${color3}. แสดงผู้ใช้ที่กำลังจะหมดอายุ (${color2}infouser${color3})"
	echo -e "${color1}17${color3}. แสดงผู้ใช้หมดอายุ (${color2}expireduser${color3})"
	echo -e "${color1}18${color3}. ลบ SSH ผู้ใช้และ OpenVPN ที่หมดอายุ (${color2}user-delete-expired${color3})"
	echo -e "${color1}19${color3}. ล็อค SSH ผู้ใช้และ OpenVPN ที่หมดอายุ (${color2}user-expire${color3})"
	echo -e "${color1}20${color3}. ดูรายการผู้ใช้ที่ถูกกรองโดยคำสั่งขีด จำกัด ของผู้ใช้ (${color2}log-limit${color3})"
	echo -e "${color1}21${color3}. ดูรายชื่อผู้ใช้ที่ห้ามใช้คำสั่งห้ามผู้ใช้ (${color2}log-ban${color3})"
	echo -e " "
	echo -e "เกี่ยวกับ PPTP VPN"
	echo -e "${color1}22${color3}. สร้างบัญชี PPTP (${color2}user-add-pptp${color3})"
	echo -e "${color1}23${color3}. ลบบัญชี PPTP (${color2}user-delete-pptp${color3})"
	echo -e "${color1}24${color3}. ดูรายละเอียดบัญชี (${color2}user-detail-pptp${color3})"
	echo -e "${color1}25${color3}. ตรวจสอบการเข้าสู่ระบบ PPTP VPN (${color2}user-login-pptp${color3})"
	echo -e "${color1}26${color3}. ดูรายชื่อบัญชีทั้งหมดของ PPTP (${color2}alluser-pptp${color3})"
	echo -e " "
	echo -e "เกี่ยวกับ VPS"
	echo -e "${color1}27${color3}. ทดสอบควาเร็วเน็ต เซิร์ฟเวอร์ (${color2}speedtest --share${color3})"
	echo -e "${color1}28${color3}. Benchmark server (${color2}bench-network${color3})"
	echo -e "${color1}29${color3}. ดูการใช้ RAM เซิร์ฟเวอร์ (${color2}ram${color3})"
if [[ "$OS" = 'debian' ]]; then 
	echo -e "${color1}30${color3}. Restart OpenSSH (${color2}service ssh restart${color3})"
	echo -e "${color1}31${color3}. Restart Dropbear (${color2}service dropbear restart${color3})"
	echo -e "${color1}32${color3}. Restart OpenVPN (${color2}service openvpn restart${color3})"
	echo -e "${color1}33${color3}. Restart PPTP VPN (${color2}service pptpd restart${color3})"
	echo -e "${color1}34${color3}. Restart Webmin (${color2}service webmin restart${color3})"
	echo -e "${color1}35${color3}. Restart Squid Proxy (${color2}service squid3 restart${color3})"
else
	echo -e "${color1}30${color3}. Restart OpenSSH (${color2}service sshd restart${color3})"
	echo -e "${color1}31${color3}. Restart Dropbear (${color2}service dropbear restart${color3})"
	echo -e "${color1}32${color3}. Restart OpenVPN (${color2}service openvpn restart${color3})"
	echo -e "${color1}33${color3}. Restart PPTP VPN (${color2}service pptpd restart${color3})"
	echo -e "${color1}34${color3}. Restart Webmin (${color2}service webmin restart${color3})"
	echo -e "${color1}35${color3}. Restart Squid Proxy (${color2}service squid restart${color3})"
fi
echo -e "${color1}36${color3}. Edit Port Server (${color2}edit-port${color3})"
echo -e "${color1}37${color3}. ตั้งค่า Auto Reboot Server (${color2}auto-reboot${color3})"
echo -e "${color1}38${color3}. Reboot server(${color2}reboot${color3})"
echo -e "${color1}39${color3}. เปลี่ยน Password VPS(${color2}passwd${color3})"
echo -e " "
echo -e "อื่นๆ เพิ่มเติม"
echo -e "${color1}40${color3}. ดูบันทึกการติดตั้ง (${color2}log-install${color3})"
echo -e "${color1}41${color3}. ดูประกาศล่าสุด (${color2}pengumuman${color3})"
echo -e "${color1}42${color3}. ดูรายการไฟล์รหัสผ่านที่ใช้ร่วมกัน (${color2}listpassword${color3})"
echo -e " "
echo -e "อัปเดต สคริปต์พรีเมี่ยม"
echo -e "${color1}43${color3}. อัปเดตเดี๋ยวนี้"
echo "-------------------------------------------"
read -p "เลือกคำสั่งที่ต้องการ (พิมพ์เลข): " x
if test $x -eq 1; then
user-add
elif test $x -eq 2; then
user-generate
elif test $x -eq 3; then
trial
elif test $x -eq 4; then
user-aktif
elif test $x -eq 5; then
user-password
elif test $x -eq 6; then
read -p "ตั้งการจำกัดการเชื่อมต่อ พิมพ์ (1-2): " MULTILOGIN
user-ban $MULTILOGIN
elif test $x -eq 7; then
user-unban
elif test $x -eq 8; then
user-lock
elif test $x -eq 9; then
user-unlock
elif test $x -eq 10; then
user-delete
elif test $x -eq 11; then
user-detail
elif test $x -eq 12; then
user-list
elif test $x -eq 13; then
user-login
elif test $x -eq 14; then
user-log
elif test $x -eq 15; then
read -p "ตั้งการจำกัดการเชื่อมต่อ พิมพ์ (1-2): " MULTILOGIN
user-limit $MULTILOGIN
elif test $x -eq 16; then
infouser
elif test $x -eq 17; then
expireduser
elif test $x -eq 18; then
user-delete-expired
elif test $x -eq 19; then
clear
echo "สคริปต์นี้จะทำงานโดยอัตโนมัติทุกๆ 12 ชั่วโมง"
echo "คุณไม่จำเป็นต้องเรียกใช้ด้วยตนเอง"
echo "หากคุณยังต้องการเรียกใช้สคริปต์นี้ให้พิมพ์ user-expire"
elif test $x -eq 20; then
log-limit
elif test $x -eq 21; then
log-ban
elif test $x -eq 22; then
user-add-pptp
elif test $x -eq 23; then
user-delete-pptp
elif test $x -eq 24; then
user-detail-pptp
elif test $x -eq 25; then
user-login-pptp
elif test $x -eq 26; then
alluser-pptp
elif test $x -eq 27; then
speedtest --share
elif test $x -eq 28; then
bench-network
elif test $x -eq 29; then
ram
elif test $x -eq 30; then
	if [[ "$OS" = 'debian' ]]; then 
		service ssh restart 
	else 
		service sshd restart 
	fi
elif test $x -eq 31; then
service dropbear restart
elif test $x -eq 32; then
service openvpn restart
elif test $x -eq 33; then
	if [[ "$OS" = 'debian' ]]; then 
		service pptpd restart 
	else 
		service pptpd restart 
	fi
elif test $x -eq 34; then
service webmin restart
elif test $x -eq 35; then
	if [[ "$OS" = 'debian' ]]; then 
		service squid3 restart 
	else 
		service squid restart 
	fi
elif test $x -eq 36; then
edit-port
elif test $x -eq 37; then
auto-reboot
elif test $x -eq 38; then
reboot
elif test $x -eq 39; then
passwd
elif test $x -eq 40; then
log-install
elif test $x -eq 41; then
pengumuman
elif test $x -eq 42; then
listpassword
elif test $x -eq 43; then
wget http://script.hostingtermurah.net/script/install-premiumscript.sh -O - -o /dev/null|sh
else
echo "ไม่พบตัวเลือกในเมนู."
exit
fi
